### ISSUE TITLE
`SentRequest` returns `Ok(None)` when peer closes.

### ISSUE THREAD

**Issue by hgaiser** [fizyr/fizyr-rpc#24]
Waiting for an update (`request.recv_update`) on a `SentRequest` results in a `Ok(None)`. According to the documentation, `Ok(None)` is expected only when a response is received instead of an update. It makes more sense to return an `IoError` in this situation.

**Comment by de-vri-es** [comment]
Looking back, this is actually on purpose. The underlying `recv_message()` does not return a Result but an Option. The idea is that I/O errors are handled in the peer run loop rather than by each request handle. For some errors, you wouldn't even know which request handle to send the error to.

But at the very least the documentation should be updated, But `recv_response()` does return a Result in case the received message was an update, and it maps None to a "connection aborted" error. That's not very consistent.

I think this needs more design to come up with a consistent and easy to use API.

**Comment by hgaiser** [comment]
If it is reflected in the API what the expected result is, then that works for me :).

**Comment by de-vri-es** [comment]
Are you sure it's not just `None` btw? `Ok(None)` seems weird.

**Comment by hgaiser** [comment]
Hmm, was a while ago, not sure on that. Maybe @vcarpani knows?

**Comment by vcarpani** [comment]
I do not remember

**Comment by de-vri-es** [comment]
Normal `SentRequestHandle.recv_update()` now returns an `Option<Message>`, so just `None`.

The generated `SentRequestHandle` structs from the `interface` macro return `Option<Result<T>>`, because the received message might fail to parse.

The idea is that in either case you can do this for plain `SentRequestHandle`:
```rust
while let Some(update) = request.recv_update() {
   ...
}

let response = request.recv_response()?;
...
```

And for generated `SentRequestHandles` that parse the message body:
```rust
while let Some(update) = request.recv_update() {
   // The update might have failed to parse, so we need to deal with that here.
   let update = match update {
      Ok(x) => x,
      Err(e) => {
          request.send_error_response("received invalid update: {}", e).await?;
          return Err(e);
      },
   })?;
   ...
}

let response = request.recv_response()?;
...
```


I think this is a good API, so I'm closing the issue. Feel free to add additional comments though, we can always revisit it.
