### ISSUE TITLE
Get credentials of connected peer

### ISSUE THREAD

**Issue by asomers** [fizyr/fizyr-rpc#29]
I would like to get the credentials of a connected peer when using a unix domain sequential packet connection.  Would you accept a PR that adds this functionality?  I can suggest three methods:

- Use the `add_creds` method that already exists in tokio-seqpacket (after extending it with BSD support)
- Use `LOCAL_PEERCRED` socket option.  This has the advantage of not requiring the peer's cooperation.
- Implement `AsRawFd` on `PeerHandle` so the consuming crate can use `LOCAL_PEERCRED` directly.

**Comment by de-vri-es** [comment]
Hmm, I would prefer to give direct access to the underlying socket so that this library can completely ignore socket specific things. Maybe not through `AsRawFd`, but more generically by giving access to the socket object so it can also be useful on Windows.

That's not necessarily easy though: a peer handle just uses a channel to communicate with an asynchronous task that really has the socket. And then that goes through an abstraction of a `Tranport` that implements the message sending/receiving. A `Transport` could easily expose the inner socket, but using that from a `PeerHandle` is more difficult. Additionally, the transport has been split in a read and write half to overcome lifetime issues we would otherwise have with TCP sockets.

Another option might be to return the peer credentials as their address when accepting a connection. It's a bit weird, but the address of a local seqpacket socket is empty anyway. At least the credentials mean something.

It might be good to discuss what you want to do before starting on it, but I'm certainly interested in supporting this.

**Comment by de-vri-es** [comment]
Hmm, I was looking into this again, and it is even harder than I initially though: PeerHandle is only generic over the message type, not over the transport type. Different transports with the same message type can have different peer "addresses" (IP+port or credentials).

So either we have to change the generic parameter of `PeerHandle` to be the transport type, or we can only do it through `Peer` and/or `Transport`, which means it can't be done anymore once the peer loop starts.

**Comment by asomers** [comment]
Yeah, that's just what I had in mind.

**Comment by de-vri-es** [comment]
The PR is merged. It will be released soon :)

**Comment by de-vri-es** [comment]
The PR is merged. It will be released soon :)

Thanks again for opening this issue!
